LIST BUG DAN PENGEMBANGAN
- PESERTA JIKA MELAKUKAN RELOAD, HARUS MENGERJAKAN DARI AWAL
- PENAMBAHAN SWAL ALERT (FIX)
- PESERTA JIKA BELUM SELESAI MENGERJAKAN SOAL, DAN SUDAH MENGIRIM JAWABAN, TOMBOL KIRIM AKAN DISABLE (FIX)
